name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Move
      run: cd PrimeService.Tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Actions Status Discord
      # You may pin to the exact commit or the version.
      # uses: sarisia/actions-status-discord@04fcc01beb0e4b4dabbd870dbdad34020051dcfa
      uses: sarisia/actions-status-discord@v1.8.3
      with:
        # Discord webhook endpoint. If not set, env.DISCORD_WEBHOOK will be used.
        webhook: https://discord.com/api/webhooks/809783065047859200/ynwn61uu_TXWVjN09iKP7vHz9bbrsYz3N54FORG4R1Kv3NSDoARH32Y-n7H7--LdQShK
        # Job status. Should be bound to job.status. Default to success.
        #status: # optional, default is ${{ job.status }}
        # Deprecated. Job name included in message title. Same as title input.
        #job: # optional
        # String included in embed title. Overrides job input.
        #title: # optional, default is ${{ github.workflow }}
        # Description included in message
        #description: # optional
        # Image attached to the message
        #image: # optional
        # Overrides Discord embed color
        #color: # optional
        # Overrides Discord webhook username
        #username: # optional
        # Overrides Discord webhook avatar url
        #avatar_url: # optional
        # This action won't make workflow failed by default.
        #nofail: # optional, default is true
        # Suppress GitHub context fields
        #nocontext: # optional, default is false
        # Avoid appending job status to title
        #noprefix: # optional, default is false
        # Suppress detailed embed fields
        #nodetail: # optional, default is false

